### ISSUE TITLE
Profile columns misaligned

### ISSUE THREAD

**Issue by Jeremy-Vidaurri** [p2sr/Portal2Boards#17]
On Firefox, the columns for WR delta are beneath the chamber title. Temp fix is to use a lower zoom level. It does not occur on Chrome.

![image](https://github.com/p2sr/Portal2Boards/assets/10247339/c1f672d3-3bf3-4459-bbe6-04d972df2f60)

**Comment by ThisAMJ** [comment]
probably because [this](https://github.com/p2sr/Portal2Boards/blob/1bfa4f8ff044f674ba3366549b520b62f240b570/public/style/style.css#L1519) and the surrounding values are hard-coded. it also needs to handle longer strings like [this guy](https://board.portal2.sr/profile/76561198118242451)
